### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by voylinux** [weskinner/symbol-gen#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0-6169caa
**System**: linux 3.13.0-45-generic
**Thrown From**: [symbol-gen](https://github.com/weskinner/symbol-gen) package, v0.1.8

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/voylinux/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:28

TypeError: undefined is not a function
  at SymbolGenView.module.exports.SymbolGenView.generate (/home/voylinux/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:28:8)
  at atom-workspace.<anonymous> (/home/voylinux/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:16:59)
  at atom-workspace.handler (/usr/local/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/local/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/local/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/local/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/local/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/local/share/atom/resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/local/share/atom/resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/local/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/local/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -1:29.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:27.8 core:backspace (atom-text-editor.editor.mini)
     -1:27.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:27.1 core:cancel (atom-text-editor.editor.mini)
     -1:25.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:16.7 core:confirm (atom-text-editor.editor.mini)
     -1:16.6 symbol-gen:generate (atom-text-editor.editor.is-focused)
     -0:03.7 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.4 core:confirm (atom-text-editor.editor.mini)
     -0:00.4 symbol-gen:generate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "goto",
      "symbols-view"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.3
color-picker, v1.4.4
editorconfig, v0.3.0
emmet, v2.3.3
linter-jshint, v0.1.0
linter-php, v0.0.11
monokai, v0.12.0
seti-ui, v0.6.3
symbol-gen, v0.1.8

# Dev
No dev packages
```

/cc @atom/core

**Comment by redrick** [comment]
hey guys, any report on this issue ? 

my search is not working now and its real pain, I was used to it :(

And those steps to reproduce are simple:
1. $ cd your/project/folder
2. $ atom .
3. press ALT+CMD+G
4. error message appears instantly :(

Thanks you guys :)

**Comment by weskinner** [comment]
Just pushed 0.2.0.  See if upgrading resolves your issue.

**Comment by redrick** [comment]
really did, thanks a million, you're awesome :)

**Comment by weskinner** [comment]
:+1:
