### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by mmochetti** [weskinner/symbol-gen#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.180.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [symbol-gen](https://github.com/weskinner/symbol-gen) package, v0.1.8

### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:423

TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:423:13)
  at SymbolGenView.module.exports.SymbolGenView.generate (/home/martin/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:34:27)
  at atom-workspace.<anonymous> (/home/martin/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:16:59)
  at atom-workspace.handler (/opt/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -5:57.4 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:55.2 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -5:36.1 core:backspace (atom-text-editor.editor.mini)
  5x -4:29.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -4:18.7 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -4:17.6 core:confirm (atom-text-editor.editor.mini)
     -4:12.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:12.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:05.3 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:04.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -4:04.3 core:cancel (atom-text-editor.editor.mini)
     -3:28.6 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  3x -3:11.9 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -0:23.4 symbols-view:toggle-project-symbols (atom-text-editor.editor.is-focused)
     -0:00.9 symbol-gen:generate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.2.3
symbol-gen, v0.1.8

# Dev
No dev packages
```

**Comment by kschaper** [comment]
**Atom Version**: 0.184.0
**System**: Mac OS X 10.9.5
**Thrown From**: [symbol-gen](https://github.com/weskinner/symbol-gen) package, v0.1.8

### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:423

TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:423:13)
  at SymbolGenView.module.exports.SymbolGenView.generate (/Users/kaischaper/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:34:27)
  at atom-workspace.<anonymous> (/Users/kaischaper/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:16:59)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:04.2 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.8 core:confirm (atom-text-editor.editor.mini)
     -0:00.7 symbol-gen:generate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "tmp",
      "tags"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "autocomplete-plus",
      "autocomplete-snippets",
      "autocomplete-paths",
      "language-php",
      "language-c",
      "language-objective-c",
      "language-perl"
    ],
    "themes": [
      "atom-light-ui",
      "quantum-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-types, v0.3.0
fonts, v0.4.0
html2haml, v0.6.0
keybinding-cheatsheet, v0.0.8
language-css-plus, v0.3.0
language-gherkin, v0.3.0
language-haml, v0.15.0
language-rspec, v0.3.0
last-cursor-position, v0.7.0
linter, v0.11.1
linter-csslint, v0.0.11
linter-eslint, v0.4.1
linter-ruby, v0.1.4
quantum-syntax, v0.2.1
symbol-gen, v0.1.8

# Dev
No dev packages
```

**Comment by sebllll** [comment]
same here. 

[Enter steps to reproduce below:]

1. install atom-ctags, symbolgen, ctags58(64bit)
2. >>generate symbols

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1
**Thrown From**: [symbol-gen](https://github.com/weskinner/symbol-gen) package, v0.2.0

### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:112

TypeError: Arguments to path.resolve must be strings
  at Object.win32.resolve (path.js:112:13)
  at SymbolGenView.module.exports.SymbolGenView.generate (C:\Users\user\.atom\packages\symbol-gen\lib\symbol-gen-view.coffee:34:27)
  at atom-workspace.<anonymous> (C:\Users\user\.atom\packages\symbol-gen\lib\symbol-gen-view.coffee:16:59)
  at atom-workspace.handler (C:\Users\user\AppData\Local\atom\app-0.182.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (C:\Users\user\AppData\Local\atom\app-0.182.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (C:\Users\user\AppData\Local\atom\app-0.182.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-0.182.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-0.182.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\user\AppData\Local\atom\app-0.182.0\resources\app\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\user\AppData\Local\atom\app-0.182.0\resources\app\src\window-event-handler.js:69:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -0:54.1 atom-sharp:open:solution:browse (atom-text-editor.editor)
     -0:03.4 symbol-gen:generate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-ctags, v2.6.1
atom-sharp, v0.1.0
autocomplete-glsl, v0.1.4
autocomplete-plus, v2.2.0
autocomplete-plus-async, v0.22.0
color-picker, v1.5.0
highlight-selected, v0.9.1
language-csharp, v0.5.0
language-glsl, v1.0.1
language-hlsl, v0.0.1
minimap, v4.3.1
minimap-color-highlight, v4.1.0
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
symbol-gen, v0.2.0

# Dev
No dev packages
```
