### ISSUE TITLE
Failed to load the symbol-gen package

### ISSUE THREAD

**Issue by djpowers** [weskinner/symbol-gen#16]
1. Just updated to Atom 0.190.0 and upon relaunch with an empty project window open, I received this error.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [symbol-gen](https://github.com/weskinner/symbol-gen) package, v0.2.0

### Stack Trace

Failed to load the symbol-gen package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/dpowers/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:4:199)
    at /Users/dpowers/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:19:5
    at Object.<anonymous> (/Users/dpowers/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:94:5)
    at Object.<anonymous> (/Users/dpowers/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:96:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "linter-scss-lint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.6.0
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-erb, v0.1.0
linter-jshint, v0.1.1
linter-ruby, v0.1.4
minimap, v4.7.6
symbol-gen, v0.2.0
vim-mode, v0.43.0

# Dev
No dev packages
```

**Comment by weskinner** [comment]
@djpowers try upgrading to 0.3.0

**Comment by djpowers** [comment]
I couldn't duplicate the original error after the first occurrence, but I haven't had any problems since updating, and it also took care of a deprecation warning I was seeing.

I'll reopen the issue if I see it again, but it seems all set. Thanks for the quick response! :+1:
